package org.openmrs.plugin.it;

import org.junit.jupiter.api.Assumptions;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.UncheckedIOException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Paths;
import java.util.Base64;
import java.util.Map;

/**
 * JUnit 5 extension that loads connection config from a .env file (or real environment
 * variables) once for the entire test suite and exposes it as static fields.
 *
 * Apply to any integration test class with @ExtendWith(OpenMrsExtension.class).
 * All tests in that class will be skipped if required config is absent.
 */
public class OpenMrsExtension implements BeforeAllCallback {

    private static final Map<String, String> DOT_ENV;

    static {
        try {
            DOT_ENV = DotEnv.load(Paths.get(System.getProperty("user.dir"), ".env"));
        } catch (IOException e) {
            throw new UncheckedIOException("Failed to load .env file", e);
        }
    }

    public static final String BASE_URL    = DotEnv.get(DOT_ENV, "OPENMRS_BASE_URL");
    public static final String USERNAME    = DotEnv.get(DOT_ENV, "OPENMRS_USERNAME");
    public static final String PASSWORD    = DotEnv.get(DOT_ENV, "OPENMRS_PASSWORD");
    public static final String SCHEMAS_DIR = firstNonBlank(
            System.getProperty("openapi.schemas.dir"),
            DotEnv.get(DOT_ENV, "OPENAPI_SCHEMAS_DIR"));

    /**
     * The servlet context path under which OpenMRS is deployed (e.g. "/openmrs").
     * OpenAPI paths generated by the plugin are relative to this context path.
     */
    public static final String CONTEXT_PATH = "/openmrs";

    public static final String AUTH_HEADER = (USERNAME != null && PASSWORD != null)
            ? "Basic " + Base64.getEncoder()
                    .encodeToString((USERNAME + ":" + PASSWORD).getBytes(StandardCharsets.UTF_8))
            : null;

    /** Simple HTTP response carrier (status code + body string). */
    public static class HttpResult {
        private final int status;
        private final String body;

        HttpResult(int status, String body) {
            this.status = status;
            this.body = body;
        }

        public int statusCode() { return status; }
        public String body()    { return body; }
    }

    public static HttpResult get(String url) throws Exception {
        return request("GET", url, null, null);
    }

    public static HttpResult post(String url, String jsonBody) throws Exception {
        return request("POST", url, "application/json", jsonBody);
    }

    public static HttpResult delete(String url) throws Exception {
        return request("DELETE", url, null, null);
    }

    private static HttpResult request(String method, String url, String contentType, String body) throws Exception {
        HttpURLConnection conn = (HttpURLConnection) new URL(url).openConnection();
        conn.setRequestMethod(method);
        conn.setRequestProperty("Authorization", AUTH_HEADER);
        if (contentType != null) {
            conn.setRequestProperty("Content-Type", contentType);
        }
        if (body != null) {
            conn.setDoOutput(true);
            try (OutputStream os = conn.getOutputStream()) {
                os.write(body.getBytes(StandardCharsets.UTF_8));
            }
        }
        int status = conn.getResponseCode();
        InputStream stream = status >= 400 ? conn.getErrorStream() : conn.getInputStream();
        String responseBody = "";
        if (stream != null) {
            responseBody = readStream(stream);
        }
        conn.disconnect();
        return new HttpResult(status, responseBody);
    }

    private static String readStream(InputStream is) throws IOException {
        ByteArrayOutputStream buf = new ByteArrayOutputStream();
        byte[] tmp = new byte[4096];
        int n;
        while ((n = is.read(tmp)) != -1) {
            buf.write(tmp, 0, n);
        }
        return buf.toString(StandardCharsets.UTF_8.name());
    }

    private static String firstNonBlank(String... values) {
        for (String v : values) {
            if (v != null && !v.trim().isEmpty()) return v;
        }
        return null;
    }

    /**
     * Called before each test class. Skips the class if required config is missing.
     */
    @Override
    public void beforeAll(ExtensionContext context) {
        Assumptions.assumeTrue(BASE_URL != null,    "Skipping: OPENMRS_BASE_URL not set (env var or .env file)");
        Assumptions.assumeTrue(USERNAME != null,    "Skipping: OPENMRS_USERNAME not set (env var or .env file)");
        Assumptions.assumeTrue(PASSWORD != null,    "Skipping: OPENMRS_PASSWORD not set (env var or .env file)");
        Assumptions.assumeTrue(SCHEMAS_DIR != null, "Skipping: openapi.schemas.dir system property not set");
    }
}
